### ISSUE TITLE
Notify user when executing at the end of the task

### ISSUE THREAD

**Issue by anubisthejackle** [alleyinteractive/wp-bulk-task#36]
### Description

Currently when you've completed a bulk task cycle the pointer is not automatically reset. I think this makes a lot of sense, but it does become a little confusing when running a CLI command again once the command has already completed once. Given any task that has reached the end of its run can not actually perform any actions, we should throw an error message to notify the end user including in it the ability to reset the pointer. This could be a request for user input that would allow us to reset the pointer immediately and then start the bulk task from the beginning.

### Use Case

When a user attempts to run a CLI command that has reached the end of its pointer an error message should be displayed notifying them that they are at the end of their pointer. User input should be accepted to either end the run, or reset the pointer to the beginning and start the command from there.

**Comment by renatonascalves** [comment]
@anubisthejackle I'd argue this should be handled by the implementer. First because the package is not CLI-specific, technically, it can be used in other scenarios.

It's better for the implementer to account for this or/and improve documentation. For example: https://github.com/alleyinteractive/wp-bulk-task/wiki#resetting-the-cursor
